config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root 'jobs#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :category
  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
  paginates_per 4

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :find_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category].blank?
    @jobs = Job.order('created_at DESC').page params[:page]
  else
    @category_id = Category.find_by(name: params[:category]).id
    @jobs = Job.where(category_id: @category_id).page params[:page]
  end
  end

def show
end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(jobs_params)
    if @job.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @job.update(jobs_params)
      redirect_to @job
    else
      render "Edit"
    end
  end

  def destroy
    @job.destroy
    redirect_to root_path
  end

  private
  def jobs_params
   params.require(:job).permit(:title, :company, :url, :category_id)
  end

  def find_job
    @job = Job.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job, html: {class: 'form-horizontal'} do |form| %>
  <%= form.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"} %>
  <%= form.input :title, label: "Job title", input_html: {class: 'form-control'} %>
  <%= form.input :company, label: "Your company", input_html: {class: 'form-control'} %>
  <%= form.input :url, label: "Link to job", input_html: {class: 'form-control'} %>
  <br>
  <%= form.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/jobs/edit.html.erb
<h1>Edit job</h1>

<%= render 'form' %>
<br>
<%= link_to "Back", root_path, class: "btn btn-primary" %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<div id = "jobs">
<% @jobs.each do |job| %>
  <div class = "job" >
    <h2><%= link_to job.title, job %></h2>
    <p><%= job.company %>
    </div>
    <% end %>
  </div>

    <%= paginate @jobs %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render "form" %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<h3><%= @job.company %></h3>
<p><%= @job.url %></p>

<%= link_to "Apply for job", @job.url, class: "btn btn-primary" %>

<br>
<br>

<div id = "links">
<%= link_to "Home", root_path, class: "btn btn-primary" %>
<% if user_signed_in? %>
<%= link_to "Edit", edit_job_path, class: "btn btn-primary" %>
<%= link_to "Delete", job_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Makazi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class = "navbar navbar-default">
    <div class = "container">
      <a class = "navbar-brand">MAKAZI</a>
      <ul class = "nav navbar-nav navbar-left">
        <li><%= link_to "All Jobs", root_path %></li>
        <% Category.all.each do |category| %>
        <li><%= link_to category.name, jobs_path(category: category.name) %></li>
        <% end %>
        <% if user_signed_in? %>
        <%= link_to "New Job", new_job_path, class: "navbar-text navbar-link" %>
        <% end %>
      </ul>

      <ul class = "nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %>
        <li><%= link_to "Log In", new_user_session_path %>
          <% end %>
      </ul>
    </div>
  </nav>

<div class = "container">
  <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
  <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>

<%= yield %>
</div>
</body>
</html>